language_dict = {
    "Afghanistan": "Pashto",
    "Albania": "Albanian",
    "Algeria": "Arabic",
    "Andorra": "Catalan",
    "Angola": "Portuguese",
    "Argentina": "Spanish",
    "Armenia": "Armenian",
    "Australia": "English",
    "Austria": "German",
    "Azerbaijan": "Azerbaijani",
    "Bangladesh": "Bengali",
    "Belgium": "Dutch",
    "Belize": "English",
    "Benin": "French",
    "Bolivia": "Spanish",
    "Bosnia and Herzegovina": "Bosnian",
    "Botswana": "English",
    "Brazil": "Portuguese",
    "Bulgaria": "Bulgarian",
    "Burkina Faso": "French",
    "Cambodia": "Khmer",
    "Cameroon": "French",
    "Canada": "English",
    "Chile": "Spanish",
    "China": "Mandarin Chinese",
    "Colombia": "Spanish",
    "Congo (Democratic Republic)": "French",
    "Costa Rica": "Spanish",
    "Croatia": "Croatian",
    "Cuba": "Spanish",
    "Cyprus": "Greek",
    "Czech Republic": "Czech",
    "Denmark": "Danish",
    "Dominican Republic": "Spanish",
    "Ecuador": "Spanish",
    "Egypt": "Arabic",
    "El Salvador": "Spanish",
    "Estonia": "Estonian",
    "Ethiopia": "Amharic",
    "Finland": "Finnish",
    "France": "French",
    "Georgia": "Georgian",
    "Germany": "German",
    "Ghana": "English",
    "Greece": "Greek",
    "Guatemala": "Spanish",
    "Haiti": "Haitian Creole",
    "Honduras": "Spanish",
    "Hungary": "Hungarian",
    "Iceland": "Icelandic",
    "India": "Hindi",
    "Indonesia": "Indonesian",
    "Iran": "Persian",
    "Iraq": "Arabic",
    "Ireland": "Irish",
    "Israel": "Hebrew",
    "Italy": "Italian",
    "Jamaica": "English",
    "Japan": "Japanese",
    "Jordan": "Arabic",
    "Kazakhstan": "Kazakh",
    "Kenya": "Swahili",
    "Kuwait": "Arabic",
    "Kyrgyzstan": "Kyrgyz",
    "Laos": "Lao",
    "Latvia": "Latvian",
    "Lebanon": "Arabic",
    "Libya": "Arabic",
    "Lithuania": "Lithuanian",
    "Luxembourg": "Luxembourgish",
    "Madagascar": "Malagasy",
    "Malaysia": "Malay",
    "Mali": "French",
    "Malta": "Maltese",
    "Mexico": "Spanish",
    "Moldova": "Romanian",
    "Monaco": "French",
    "Mongolia": "Mongolian",
    "Montenegro": "Montenegrin",
    "Morocco": "Arabic",
    "Mozambique": "Portuguese",
    "Myanmar": "Burmese",
    "Nepal": "Nepali",
    "Netherlands": "Dutch",
    "New Zealand": "English",
    "Nicaragua": "Spanish",
    "Nigeria": "English",
    "North Korea": "Korean",
    "Norway": "Norwegian",
    "Oman": "Arabic",
    "Pakistan": "Urdu",
    "Panama": "Spanish",
    "Paraguay": "Spanish",
    "Peru": "Spanish",
    "Philippines": "Filipino",
    "Poland": "Polish",
    "Portugal": "Portuguese",
    "Qatar": "Arabic",
    "Romania": "Romanian",
    "Russia": "Russian",
    "Rwanda": "Kinyarwanda",
    "Saudi Arabia": "Arabic",
    "Senegal": "French",
    "Serbia": "Serbian",
    "Singapore": "English",
    "Slovakia": "Slovak",
    "Slovenia": "Slovene",
    "South Africa": "Zulu",
    "South Korea": "Korean",
    "Spain": "Spanish",
    "Sri Lanka": "Sinhala",
    "Sudan": "Arabic",
    "Sweden": "Swedish",
    "Switzerland": "German",
    "Syria": "Arabic",
    "Taiwan": "Mandarin Chinese",
    "Tajikistan": "Tajik",
    "Tanzania": "Swahili",
    "Thailand": "Thai",
    "Tunisia": "Arabic",
    "Turkey": "Turkish",
    "Turkmenistan": "Turkmen",
    "Uganda": "Swahili",
    "Ukraine": "Ukrainian",
    "United Arab Emirates": "Arabic",
    "United Kingdom": "English",
    "United States": "English",
    "Uruguay": "Spanish",
    "Uzbekistan": "Uzbek",
    "Venezuela": "Spanish",
    "Vietnam": "Vietnamese",
    "Yemen": "Arabic",
    "Zambia": "English",
    "Zimbabwe": "Shona",
    "Palestine": "Arabic",
    "Hong Kong": "Cantonese",
    "Macau": "Cantonese",
    "Kosovo": "Albanian"
}

all_languages = list(set(language_dict.values()))


language_dict_google = {
    "Afghanistan": "ps",
    "Albania": "sq",
    "Algeria": "ar",
    "Andorra": "ca",
    "Angola": "pt",
    "Argentina": "es",
    "Armenia": "hy",
    "Australia": "en",
    "Austria": "de",
    "Azerbaijan": "az",
    "Bangladesh": "bn",
    "Belgium": "nl",
    "Belize": "en",
    "Benin": "fr",
    "Bhutan": "en", 
    "Bolivia": "es",
    "Bosnia and Herzegovina": "bs",
    "Botswana": "en",
    "Brazil": "pt",
    "Bulgaria": "bg",
    "Burkina Faso": "fr",
    "Cambodia": "km",
    "Cameroon": "fr",
    "Canada": "en",
    "Chile": "es",
    "China": "zh-CN",
    "Colombia": "es",
    "Congo (Democratic Republic)": "fr",
    "Costa Rica": "es",
    "Croatia": "hr",
    "Cuba": "es",
    "Cyprus": "el",
    "Czech Republic": "cs",
    "Denmark": "da",
    "Dominican Republic": "es",
    "Ecuador": "es",
    "Egypt": "ar",
    "El Salvador": "es",
    "Estonia": "et",
    "Ethiopia": "am",
    "Finland": "fi",
    "France": "fr",
    "Georgia": "ka",
    "Germany": "de",
    "Ghana": "en",
    "Greece": "el",
    "Guatemala": "es",
    "Haiti": "ht",
    "Honduras": "es",
    "Hungary": "hu",
    "Iceland": "is",
    "India": "hi",
    "Indonesia": "id",
    "Iran": "fa",
    "Iraq": "ar",
    "Ireland": "ga",
    "Israel": "iw",
    "Italy": "it",
    "Jamaica": "en",
    "Japan": "ja",
    "Jordan": "ar",
    "Kazakhstan": "kk",
    "Kenya": "sw",
    "Kuwait": "ar",
    "Kyrgyzstan": "ky",
    "Laos": "lo",
    "Latvia": "lv",
    "Lebanon": "ar",
    "Libya": "ar",
    "Lithuania": "lt",
    "Luxembourg": "lb",
    "Madagascar": "mg",
    "Malaysia": "ms",
    "Mali": "fr",
    "Malta": "mt",
    "Mexico": "es",
    "Moldova": "ro",
    "Monaco": "fr",
    "Mongolia": "mn",
    "Montenegro": "sr",
    "Morocco": "ar",
    "Mozambique": "pt",
    "Myanmar": "my",
    "Nepal": "ne",
    "Netherlands": "nl",
    "New Zealand": "en",
    "Nicaragua": "es",
    "Nigeria": "en",
    "North Korea": "ko",
    "Norway": "no",
    "Oman": "ar",
    "Pakistan": "ur",
    "Panama": "es",
    "Paraguay": "es",
    "Peru": "es",
    "Philippines": "tl",
    "Poland": "pl",
    "Portugal": "pt",
    "Qatar": "ar",
    "Romania": "ro",
    "Russia": "ru",
    "Rwanda": "rw",
    "Saudi Arabia": "ar",
    "Senegal": "fr",
    "Serbia": "sr",
    "Singapore": "en",
    "Slovakia": "sk",
    "Slovenia": "sl",
    "South Africa": "zu",
    "South Korea": "ko",
    "Spain": "es",
    "Sri Lanka": "si",
    "Sudan": "ar",
    "Sweden": "sv",
    "Switzerland": "de",
    "Syria": "ar",
    "Taiwan": "zh-TW",
    "Tajikistan": "tg",
    "Tanzania": "sw",
    "Thailand": "th",
    "Tunisia": "ar",
    "Turkey": "tr",
    "Turkmenistan": "tk",
    "Uganda": "sw",
    "Ukraine": "uk",
    "United Arab Emirates": "ar",
    "United Kingdom": "en",
    "United States": "en",
    "Uruguay": "es",
    "Uzbekistan": "uz",
    "Venezuela": "es",
    "Vietnam": "vi",
    "Yemen": "ar",
    "Zambia": "en",
    "Zimbabwe": "sn",
    "Palestine": "ar",
    "Hong Kong": "zh-TW",   # Cantonese not supported → Traditional Chinese
    "Macau": "zh-TW",       # same reasoning
    "Kosovo": "sq"
}